Align module with Snowflake provider changes
getindata/terraform-snowflake-database pull request #34
Opened 2024-07-30 11:33 UTC by moss2k13

## BREAKING CHANGES IN v2.x.x
Due to breaking changes in Snowflake provider and additional code optimizations, **breaking changes** were introduced in `v2.0.0` version of this module.

List of code and variable (API) changes:
- Switched to `snowflake_database_role` module to leverage new `database_roles` mechanism
- `default_roles` and `custom_roles` are now combined and controlled by single logic in nowflake_database_role module
- snowflake_database resource was updated to use newly introduced changes in Snowflake rovider
- snowflake_schema resource was updated to use newly introduced changes in Snowflake rovider
- variable `add_grants_to_existing_objects` was removed as it is no longer needed
- minimum Snowflake provider version is `0.90.0`

For more information, refer to [variables.tf](variables.tf), list of inputs below and nowflake provider documentation

When upgrading from `v1.x`, expect most of the resources to be recreated - if recreation is impossible, then it is possible to import some existing resources.

2024-07-30 11:34 UTC, moss2k13 commented on main.tf
> +  version = "v2.0.0"
depends on https://github.com/getindata/terraform-snowflake-schema/pull/25

2024-07-31 07:38 UTC, dgniewek commented on variables.tf
> +      create_default_stage_roles = optional(bool)
We're keeping that unified everywhere, so rollback to `create_default_roles` instead of `create_default_stage_roles`

2024-08-01 10:14 UTC, dgniewek commented on locals.tf
> +        all_schemas_in_database = true
It is missimg future_schemas, which are actually more important here

2024-08-01 10:14 UTC, dgniewek commented on locals.tf
> +      schema_grants = [{
It is missing future_schemas, which are actually more important here

2024-08-01 10:19 UTC, dgniewek commented on main.tf
>    attributes = [one(snowflake_database.this[*].name)]
Pls - do not pass DB name to the role, since those will be DB roles, the DB name is implied :)

2024-08-01 10:19 UTC, dgniewek commented on main.tf
>    attributes = [one(snowflake_database.this[*].name)]
The same comment as above - do not pass a DB name to role label

2024-08-01 10:22 UTC, dgniewek commented on variables.tf
> +    database_grants = optional(object({
Pls pass `descriptor_name      = optional(string, "snowflake-database-role")`

2024-08-01 10:23 UTC, dgniewek commented on variables.tf
>          granted_roles        = optional(list(string))
Pls pass `descriptor_name      = optional(string, "snowflake-database-role")`

2024-08-01 10:23 UTC, dgniewek commented on variables.tf
> +      descriptor_name      = optional(string, "snowflake-role")
Pls pass `descriptor_name      = optional(string, "snowflake-database-role")`

2024-08-01 10:29 UTC, dgniewek commented on variables.tf
> +      table_grants             = optional(list(string))
seems like variables are not updated accrodingly

2024-08-01 10:30 UTC, dgniewek commented on main.tf
> +  schema_grants             = lookup(each.value, "schema_grants", [])
seems like you're missing `schema_object_grants` support here

2024-08-01 10:31 UTC, dgniewek commented on variables.tf
> +      table_grants             = optional(list(string))
You're missing `schema_objects_grants` here also

2024-08-01 10:32 UTC, dgniewek commented on variables.tf
> +        })))
`schemas_objects_grants` is missing here

2024-08-01 12:31 UTC, dpnoworyta commented on locals.tf
Could you please combine line 8 and 9 in this file?

2024-08-02 11:35 UTC, dgniewek requested changes

2024-08-02 11:41 UTC, dgniewek requested changes

2024-08-02 11:41 UTC, dgniewek commented on main.tf
> +  version = "2.0.0"
Pls bump to newest version

2024-08-02 11:41 UTC, dgniewek commented on variables.tf
>        roles = optional(map(object({
Align with the newest version of  `snowflake-schema`

2024-08-05 06:48 UTC, dgniewek requested changes

2024-08-05 06:48 UTC, dgniewek commented on variables.tf
> +  description = "The fully qualified name of the account role to which database privileges will be granted"
Account role doesn't have a fully qulified name :)

2024-08-05 06:48 UTC, dgniewek commented on variables.tf
> +variable "database_ownership_account_role_name" {
Please rename it to `database_ownership_grany`

2024-08-05 06:48 UTC, dgniewek commented on outputs.tf
> +output "database_ownership_account_role_name" {
`database_ownership_grant`

2024-08-05 07:43 UTC, dgniewek approved these changes

2024-08-05 08:12 UTC, merged